/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Datos.Cliente;
import Datos.Estudiante;
import Datos.LectorDeLibros;
import Datos.Producto;
import Datos.Profesor;
import Logica.Kiosko;
import Logica.KioskoException;
import Logica.Secretario;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Ernesto
 */
public class PantallaConfirmacionLector extends javax.swing.JFrame {
    private JFrame principal;
    Kiosko tienda;
    Cliente auxCliente;
    Producto auxProducto;
    int posTarjeta;
    int productoNum;
    String usuario;
    /**
     * Creates new form PantallaConfirmacion
     */
    public PantallaConfirmacionLector(JFrame ventana,Kiosko tienda, int productoNum, String usuario) {
        initComponents();
        principal = ventana;
        principal.setVisible(true);
        setSize(400, 600);
        this.setVisible(true);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        getContentPane().setBackground(new java.awt.Color(220, 200, 240));
        
        
        jLabelNombreUsuario.setText(usuario);
        auxCliente = Kiosko.getUsuariosRegistrados().get(usuario);
        auxProducto = Kiosko.getLectoresDisponibles().get(productoNum);
        posTarjeta = 0;
        

        if (auxCliente.getTarjetero().isEmpty()) {
            jTextFieldCCV.setText(" ");
            jTextFieldFecha.setText(" ");
            jTextFieldNombre.setText(" ");
            jTextFieldNumero.setText(" ");
        } else {

            jTextFieldCCV.setText(auxCliente.getTarjetero().get(posTarjeta).getCcvString());
            jTextFieldFecha.setText(auxCliente.getTarjetero().get(posTarjeta).getFechaCaducidadString());
            jTextFieldNombre.setText(auxCliente.getTarjetero().get(posTarjeta).getNombre());
            jTextFieldNumero.setText(auxCliente.getTarjetero().get(posTarjeta).getNumeroString());
            jButtonComprar.setEnabled(true);
        }

        
            jToggleButtonEpub.setVisible(false);
            jToggleButtonMobi.setVisible(false);
            jToggleButtonPdf.setVisible(false);
            jSpinnerMeses.setVisible(false);
            jButtonConsultaOnline.setVisible(false);
        

    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButtonComprar = new javax.swing.JButton();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldNumero = new javax.swing.JTextField();
        jTextFieldFecha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCCV = new javax.swing.JTextField();
        jLabelNombreUsuario = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jToggleButtonEpub = new javax.swing.JToggleButton();
        jToggleButtonMobi = new javax.swing.JToggleButton();
        jToggleButtonPdf = new javax.swing.JToggleButton();
        jButtonConsultaOnline = new javax.swing.JButton();
        jSpinnerMeses = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonComprar.setText("Comprar");
        jButtonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Numero");

        jLabel3.setText("Fecha Caducidad");

        jLabel4.setText("CCV");

        jLabelNombreUsuario.setText("jLabel5");

        jLabel5.setText("Tarjeta de Credito de usuario:");

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButtonEpub);
        jToggleButtonEpub.setText("epub");

        buttonGroup1.add(jToggleButtonMobi);
        jToggleButtonMobi.setText("mobi");

        buttonGroup1.add(jToggleButtonPdf);
        jToggleButtonPdf.setText("pdf");

        jButtonConsultaOnline.setText("Consulta Online");
        jButtonConsultaOnline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaOnlineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldFecha)
                                .addComponent(jTextFieldCCV, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonComprar, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSpinnerMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonConsultaOnline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jToggleButtonEpub, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jToggleButtonMobi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jToggleButtonPdf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(105, 105, 105)
                                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 26, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldCCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jButtonCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jToggleButtonEpub)
                        .addGap(11, 11, 11)
                        .addComponent(jToggleButtonMobi)
                        .addGap(11, 11, 11)
                        .addComponent(jToggleButtonPdf)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonComprar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConsultaOnline)
                    .addComponent(jSpinnerMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprarActionPerformed
        // TODO add your handling code here:

        if (auxCliente instanceof Estudiante) {
            try {
                ((Estudiante) auxCliente).comprar(auxProducto, posTarjeta);
                this.setVisible(false);
            } catch (KioskoException ex) {
                Logger.getLogger(PantallaConfirmacionLector.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else /*(auxCliente instanceof Profesor)*/ {
            try {
                ((Profesor) auxCliente).comprar(auxProducto, posTarjeta);
                this.setVisible(false);
            } catch (KioskoException ex) {
                Logger.getLogger(PantallaConfirmacionLector.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    
    }//GEN-LAST:event_jButtonComprarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        principal.setVisible(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonConsultaOnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaOnlineActionPerformed
        // TODO add your handling code here:
          if (auxCliente instanceof Estudiante) {
            try {
                ((Estudiante) auxCliente).consultaOnline(auxProducto, posTarjeta,Integer.getInteger(jSpinnerMeses.getToolTipText()));
                this.setVisible(false);
            } catch (KioskoException ex) {
                Logger.getLogger(PantallaConfirmacionLector.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else /*(auxCliente instanceof Profesor)*/ {
            try {
                ((Profesor) auxCliente).consultaOnline(auxProducto, posTarjeta,Integer.getInteger(jSpinnerMeses.getToolTipText()));
                this.setVisible(false);
            } catch (KioskoException ex) {
                Logger.getLogger(PantallaConfirmacionLector.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jButtonConsultaOnlineActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonComprar;
    private javax.swing.JButton jButtonConsultaOnline;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelNombreUsuario;
    private javax.swing.JSpinner jSpinnerMeses;
    private javax.swing.JTextField jTextFieldCCV;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JToggleButton jToggleButtonEpub;
    private javax.swing.JToggleButton jToggleButtonMobi;
    private javax.swing.JToggleButton jToggleButtonPdf;
    // End of variables declaration//GEN-END:variables
}
