/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Datos.Estudiante;
import Datos.LectorDeLibros;
import Datos.Profesor;
import Datos.PublicacionDigital;
import Logica.Kioskero;
import Logica.Kiosko;
import Logica.KioskoException;
import Logica.Secretario;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ernesto
 */
public class PantallaInicio extends javax.swing.JFrame {

    private Kiosko tienda;
    int productoNum;
    int productoNumLec;
    int productoBusqueda;

    /**
     * Creates new form PantallaInicio
     */
    public PantallaInicio() {

        initComponents();

        setSize(860, 600);
        getContentPane().setBackground(new java.awt.Color(200, 200, 250));
        this.setVisible(true);
        setResizable(false);
        setTitle("Libreria Online");
        jLabelUsusarioIniciado.setText("Anonimo");

        tienda = new Kiosko();
        Kiosko.cargarDatos();
        Kiosko.cargarDatosLectores();
        Kiosko.cargarDatosLibros();
        Kiosko.cargarDatosVentas();
        
        jButtonConfiguracion.setEnabled(false);
        jButtonSalir.setEnabled(false);

        
        jTextFieldPanelTitulo.setText(((PublicacionDigital) (Kiosko.getProductosDisponibles().get(productoNum))).getTitulo());
        jTextFieldPanelAutor.setText(((PublicacionDigital) (Kiosko.getProductosDisponibles().get(productoNum))).getAutor());
        jTextFieldPanelEditorial.setText(((PublicacionDigital) (Kiosko.getProductosDisponibles().get(productoNum))).getEditorial());
        jTextFieldPanelPrecio.setText(Double.toString(Kiosko.getProductosDisponibles().get(productoNum).getPrecio()) + " Euros");

        jTextFieldPanelMarca.setText(((LectorDeLibros) (Kiosko.getLectoresDisponibles().get(productoNumLec))).getMarca());
        jTextFieldPanelModelo.setText(((LectorDeLibros) (Kiosko.getLectoresDisponibles().get(productoNumLec))).getModelo());
        jTextFieldPanelPrecio2.setText(Double.toString(Kiosko.getLectoresDisponibles().get(productoNumLec).getPrecio()) + " Euros");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRegistro = new javax.swing.JButton();
        jButtonBusqueda = new javax.swing.JButton();
        jTextFieldBusqueda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jButtonIniciarSesion = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabelUsusarioIniciado = new javax.swing.JLabel();
        jButtonConfiguracion = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jButtonPanelAtras = new javax.swing.JButton();
        jButtonPanelSiguiente = new javax.swing.JButton();
        jButtonSiguientelibro = new javax.swing.JButton();
        jButtonAtrasLector = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPanelTitulo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldPanelAutor = new javax.swing.JTextField();
        jTextFieldPanelEditorial = new javax.swing.JTextField();
        jTextFieldPanelPrecio = new javax.swing.JTextField();
        jButtonVerlibro = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldPanelMarca = new javax.swing.JTextField();
        jTextFieldPanelModelo = new javax.swing.JTextField();
        jTextFieldPanelPrecio2 = new javax.swing.JTextField();
        jButtonVerLector = new javax.swing.JButton();
        jButtonBusquedaAvanzada = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonBusquedaSiguiente = new javax.swing.JButton();
        jButtonBusquedaAnterior = new javax.swing.JButton();
        jButtonBusquedaVer = new javax.swing.JButton();
        jButtonLimpiarBusqueda = new javax.swing.JButton();
        jButtonAdministracion = new javax.swing.JButton();
        jTextFieldPrecioMax = new javax.swing.JTextField();
        jButtonBusquedaPorPrecio = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jButtonRegistro.setText("Registro");
        jButtonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistroActionPerformed(evt);
            }
        });

        jButtonBusqueda.setText("Busqueda");
        jButtonBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBusquedaActionPerformed(evt);
            }
        });

        jLabel1.setText("¿No te has registrado aún?");

        jLabel2.setText("Usuario");

        jLabel3.setText("Contraseña");

        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });

        jButtonIniciarSesion.setText("Inicio");
        jButtonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarSesionActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jLabel4.setText("Sesion iniciada por:");

        jButtonConfiguracion.setText("Configurar Cuenta");
        jButtonConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfiguracionActionPerformed(evt);
            }
        });

        jSeparator1.setPreferredSize(new java.awt.Dimension(150, 10));

        jButtonPanelAtras.setText("Atras");
        jButtonPanelAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPanelAtrasActionPerformed(evt);
            }
        });

        jButtonPanelSiguiente.setText("Siguiente");
        jButtonPanelSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPanelSiguienteActionPerformed(evt);
            }
        });

        jButtonSiguientelibro.setText("Siguiente");
        jButtonSiguientelibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguientelibroActionPerformed(evt);
            }
        });

        jButtonAtrasLector.setText("Atras");
        jButtonAtrasLector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasLectorActionPerformed(evt);
            }
        });

        jLabel5.setText("Titulo");

        jTextFieldPanelTitulo.setEditable(false);
        jTextFieldPanelTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPanelTituloActionPerformed(evt);
            }
        });

        jLabel6.setText("Autor");

        jLabel7.setText("Editorial");

        jLabel8.setText("Precio");

        jButtonVerlibro.setText("Ver");
        jButtonVerlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerlibroActionPerformed(evt);
            }
        });

        jLabel9.setText("Marca");

        jLabel10.setText("Modelo");

        jLabel11.setText("Precio");

        jButtonVerLector.setText("Ver");
        jButtonVerLector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerLectorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPanelAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAtrasLector, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldPanelAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(jTextFieldPanelTitulo)
                        .addComponent(jTextFieldPanelEditorial)
                        .addComponent(jTextFieldPanelPrecio)
                        .addComponent(jButtonVerlibro, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldPanelMarca)
                        .addComponent(jTextFieldPanelModelo)
                        .addComponent(jTextFieldPanelPrecio2))
                    .addComponent(jButtonVerLector, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPanelSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(jButtonSiguientelibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPanelAtras, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(jButtonSiguientelibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPanelSiguiente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAtrasLector, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldPanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldPanelAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldPanelEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldPanelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonVerlibro)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldPanelMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPanelModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPanelPrecio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(16, 16, 16)
                .addComponent(jButtonVerLector))
        );

        jButtonBusquedaAvanzada.setText("Avanzada");
        jButtonBusquedaAvanzada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBusquedaAvanzadaActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButtonBusquedaSiguiente.setText("Siguiente");
        jButtonBusquedaSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBusquedaSiguienteActionPerformed(evt);
            }
        });

        jButtonBusquedaAnterior.setText("Anterior");
        jButtonBusquedaAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBusquedaAnteriorActionPerformed(evt);
            }
        });

        jButtonBusquedaVer.setText("Ver");
        jButtonBusquedaVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBusquedaVerActionPerformed(evt);
            }
        });

        jButtonLimpiarBusqueda.setText("Limpiar");
        jButtonLimpiarBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarBusquedaActionPerformed(evt);
            }
        });

        jButtonAdministracion.setText("ADMIN");
        jButtonAdministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdministracionActionPerformed(evt);
            }
        });

        jButtonBusquedaPorPrecio.setText("Precio Max");
        jButtonBusquedaPorPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBusquedaPorPrecioActionPerformed(evt);
            }
        });

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(jPasswordField1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonConfiguracion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonRegistro))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabelUsusarioIniciado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addComponent(jLabel1))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldBusqueda)
                    .addComponent(jButtonBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBusquedaAvanzada, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonBusquedaSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBusquedaAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBusquedaVer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLimpiarBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButtonAdministracion, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldPrecioMax)
                    .addComponent(jButtonBusquedaPorPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonAdministracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabelUsusarioIniciado))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonRegistro)
                            .addComponent(jLabel3)
                            .addComponent(jButtonConfiguracion)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jButtonIniciarSesion))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSalir))))
                .addGap(15, 15, 15)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBusqueda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBusquedaAvanzada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPrecioMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonBusquedaPorPrecio)
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBusquedaSiguiente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBusquedaAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBusquedaVer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLimpiarBusqueda))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistroActionPerformed
        // TODO add your handling code here:
        PantallaRegistro a = new PantallaRegistro(this, tienda);
    }//GEN-LAST:event_jButtonRegistroActionPerformed

    private void jButtonBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBusquedaActionPerformed
        // TODO add your handling code here:

        jTextArea1.setText("");
        String comando = jTextFieldBusqueda.getText();
        Kioskero igor = Kioskero.getInstance();
        try {
            igor.busqueda(comando, Kiosko.getProductosDisponibles(), Kiosko.getLosResultados());
            jTextArea1.setLineWrap(true);
            jTextArea1.setWrapStyleWord(true);
            jTextArea1.setText(Kiosko.getLosResultados().get((Kiosko.getLosResultados().size()) - 1).toString());
            productoBusqueda = (Kiosko.getLosResultados().size()) - 1;
        } catch (KioskoException ex) {
            Logger.getLogger(PantallaInicio.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButtonBusquedaActionPerformed

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jButtonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarSesionActionPerformed
        // TODO add your handling code here:
        Secretario alfred = Secretario.getInstance();
        if (alfred.existeUsuario(jTextFieldUsuario.getText(), Kiosko.getUsuariosRegistrados()) && (jPasswordField1.getPassword().equals(Kiosko.getUsuariosRegistrados().get(jTextFieldUsuario.getText()).getPassword()))) {
            String tipo = Kiosko.getUsuariosRegistrados().get(jTextFieldUsuario.getText()).getClass().getSimpleName();
            if (tipo.equals("Estudiante")) {
                Kiosko.setAuxEstudiante((Estudiante) Kiosko.getUsuariosRegistrados().get(jTextFieldUsuario.getText()));
            } else {
                Kiosko.setAuxProfesor((Profesor) Kiosko.getUsuariosRegistrados().get(jTextFieldUsuario.getText()));
            }
            jLabelUsusarioIniciado.setText(Kiosko.getUsuariosRegistrados().get(jTextFieldUsuario.getText()).getNick());
            jButtonIniciarSesion.setEnabled(false);
            jButtonConfiguracion.setEnabled(true);
            jButtonSalir.setEnabled(true);

            
            jTextFieldUsuario.setText("");
            jPasswordField1.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Asegurese de que el usuario y contraseña son correctos", "Error", JOptionPane.ERROR_MESSAGE);
            jTextFieldUsuario.setText("");
            jPasswordField1.setText("");
        }

    }//GEN-LAST:event_jButtonIniciarSesionActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        jLabelUsusarioIniciado.setText("Anonimo");
        jButtonIniciarSesion.setEnabled(true);
        jButtonConfiguracion.setEnabled(false);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonPanelAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPanelAtrasActionPerformed
        // TODO add your handling code here:
        if (productoNum > 0) {
            productoNum = productoNum - 1;
            jTextFieldPanelTitulo.setText(((PublicacionDigital) (Kiosko.getProductosDisponibles().get(productoNum))).getTitulo());
            jTextFieldPanelAutor.setText(((PublicacionDigital) (Kiosko.getProductosDisponibles().get(productoNum))).getAutor());
            jTextFieldPanelEditorial.setText(((PublicacionDigital) (Kiosko.getProductosDisponibles().get(productoNum))).getEditorial());
            jTextFieldPanelPrecio.setText(Double.toString(Kiosko.getProductosDisponibles().get(productoNum).getPrecio()) + " Euros");
        } else {
            productoNum = Kiosko.getProductosDisponibles().size() - 1;
            jTextFieldPanelTitulo.setText(((PublicacionDigital) (Kiosko.getProductosDisponibles().get(productoNum))).getTitulo());
            jTextFieldPanelAutor.setText(((PublicacionDigital) (Kiosko.getProductosDisponibles().get(productoNum))).getAutor());
            jTextFieldPanelEditorial.setText(((PublicacionDigital) (Kiosko.getProductosDisponibles().get(productoNum))).getEditorial());
            jTextFieldPanelPrecio.setText(Double.toString(Kiosko.getProductosDisponibles().get(productoNum).getPrecio()) + " Euros");
        }
    }//GEN-LAST:event_jButtonPanelAtrasActionPerformed

    private void jTextFieldPanelTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPanelTituloActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jTextFieldPanelTituloActionPerformed

    private void jButtonSiguientelibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguientelibroActionPerformed
        // TODO add your handling code here:
        if (productoNum == Kiosko.getProductosDisponibles().size() - 1) {
            productoNum = 0;
            jTextFieldPanelTitulo.setText(((PublicacionDigital) (Kiosko.getProductosDisponibles().get(productoNum))).getTitulo());
            jTextFieldPanelAutor.setText(((PublicacionDigital) (Kiosko.getProductosDisponibles().get(productoNum))).getAutor());
            jTextFieldPanelEditorial.setText(((PublicacionDigital) (Kiosko.getProductosDisponibles().get(productoNum))).getEditorial());
            jTextFieldPanelPrecio.setText(Double.toString(Kiosko.getProductosDisponibles().get(productoNum).getPrecio()) + " Euros");
        } else {
            productoNum = productoNum + 1;
            jTextFieldPanelTitulo.setText(((PublicacionDigital) (Kiosko.getProductosDisponibles().get(productoNum))).getTitulo());
            jTextFieldPanelAutor.setText(((PublicacionDigital) (Kiosko.getProductosDisponibles().get(productoNum))).getAutor());
            jTextFieldPanelEditorial.setText(((PublicacionDigital) (Kiosko.getProductosDisponibles().get(productoNum))).getEditorial());
            jTextFieldPanelPrecio.setText(Double.toString(Kiosko.getProductosDisponibles().get(productoNum).getPrecio()) + " Euros");
        }
    }//GEN-LAST:event_jButtonSiguientelibroActionPerformed

    private void jButtonAtrasLectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasLectorActionPerformed
        // TODO add your handling code here:

        if (productoNumLec > 0) {
            productoNumLec = productoNumLec - 1;
            jTextFieldPanelMarca.setText(((LectorDeLibros) (Kiosko.getLectoresDisponibles().get(productoNumLec))).getMarca());
            jTextFieldPanelModelo.setText(((LectorDeLibros) (Kiosko.getLectoresDisponibles().get(productoNumLec))).getModelo());
            jTextFieldPanelPrecio2.setText(Double.toString(Kiosko.getLectoresDisponibles().get(productoNumLec).getPrecio()) + " Euros");
        } else {
            productoNumLec = Kiosko.getLectoresDisponibles().size() - 1;
            jTextFieldPanelMarca.setText(((LectorDeLibros) (Kiosko.getLectoresDisponibles().get(productoNumLec))).getMarca());
            jTextFieldPanelModelo.setText(((LectorDeLibros) (Kiosko.getLectoresDisponibles().get(productoNumLec))).getModelo());
            jTextFieldPanelPrecio2.setText(Double.toString(Kiosko.getLectoresDisponibles().get(productoNumLec).getPrecio()) + " Euros");
        }
    }//GEN-LAST:event_jButtonAtrasLectorActionPerformed

    private void jButtonPanelSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPanelSiguienteActionPerformed
        // TODO add your handling code here:
        if (productoNumLec == Kiosko.getLectoresDisponibles().size() - 1) {
            productoNumLec = 0;
            jTextFieldPanelMarca.setText(((LectorDeLibros) (Kiosko.getLectoresDisponibles().get(productoNumLec))).getMarca());
            jTextFieldPanelModelo.setText(((LectorDeLibros) (Kiosko.getLectoresDisponibles().get(productoNumLec))).getModelo());
            jTextFieldPanelPrecio2.setText(Double.toString(Kiosko.getLectoresDisponibles().get(productoNumLec).getPrecio()) + " Euros");
        } else {
            productoNumLec = productoNumLec + 1;
            jTextFieldPanelMarca.setText(((LectorDeLibros) (Kiosko.getLectoresDisponibles().get(productoNumLec))).getMarca());
            jTextFieldPanelModelo.setText(((LectorDeLibros) (Kiosko.getLectoresDisponibles().get(productoNumLec))).getModelo());
            jTextFieldPanelPrecio2.setText(Double.toString(Kiosko.getLectoresDisponibles().get(productoNumLec).getPrecio()) + " Euros");
        }

    }//GEN-LAST:event_jButtonPanelSiguienteActionPerformed

    private void jButtonVerlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerlibroActionPerformed
        // TODO add your handling code here:

        PantallaLibro b = new PantallaLibro(this, tienda, productoNum, jLabelUsusarioIniciado.getText());
        this.setVisible(false);
    }//GEN-LAST:event_jButtonVerlibroActionPerformed

    private void jButtonBusquedaAvanzadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBusquedaAvanzadaActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
        String comando = jTextFieldBusqueda.getText();
        Kioskero igor = Kioskero.getInstance();
        Secretario alfred = Secretario.getInstance();
        ArrayList<String> busqueda;

        busqueda = alfred.separaLaCadena(comando);

        try {
            igor.busquedaAvanzada(busqueda, Kiosko.getProductosDisponibles(), Kiosko.getLosResultados());
            jTextArea1.setLineWrap(true);
            jTextArea1.setWrapStyleWord(true);
            jTextArea1.setText(Kiosko.getLosResultados().get((Kiosko.getLosResultados().size()) - 1).toString());
            productoBusqueda = (Kiosko.getLosResultados().size()) - 1;
        } catch (KioskoException ex) {
            Logger.getLogger(PantallaInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonBusquedaAvanzadaActionPerformed

    private void jButtonBusquedaSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBusquedaSiguienteActionPerformed
        // TODO add your handling code here:

        if (productoBusqueda == Kiosko.getLosResultados().size() - 1) {
            productoBusqueda = 0;
            jTextArea1.setLineWrap(true);
            jTextArea1.setWrapStyleWord(true);
            jTextArea1.setText(Kiosko.getLosResultados().get(productoBusqueda).toString());

        } else {
            productoBusqueda = productoBusqueda + 1;
            jTextArea1.setLineWrap(true);
            jTextArea1.setWrapStyleWord(true);
            jTextArea1.setText(Kiosko.getLosResultados().get(productoBusqueda).toString());
        }
    }//GEN-LAST:event_jButtonBusquedaSiguienteActionPerformed

    private void jButtonBusquedaAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBusquedaAnteriorActionPerformed
        // TODO add your handling code here:
        if (productoBusqueda > 0) {
            productoBusqueda = productoBusqueda - 1;
            jTextArea1.setLineWrap(true);
            jTextArea1.setWrapStyleWord(true);
            jTextArea1.setText(Kiosko.getLosResultados().get(productoBusqueda).toString());
        } else {
            productoBusqueda = Kiosko.getProductosDisponibles().size() - 1;
            jTextArea1.setLineWrap(true);
            jTextArea1.setWrapStyleWord(true);
            jTextArea1.setText(Kiosko.getLosResultados().get(productoBusqueda).toString());
        }
    }//GEN-LAST:event_jButtonBusquedaAnteriorActionPerformed

    private void jButtonBusquedaVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBusquedaVerActionPerformed
        // TODO add your handling code here:
        if (Kiosko.getLosResultados().get(productoBusqueda) instanceof LectorDeLibros) {
            PantallaLector b = new PantallaLector(this, tienda, productoBusqueda, jLabelUsusarioIniciado.getText());
        } else {
            PantallaLibro b = new PantallaLibro(this, tienda, productoBusqueda, jLabelUsusarioIniciado.getText());
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBusquedaVerActionPerformed

    private void jButtonLimpiarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarBusquedaActionPerformed
        // TODO add your handling code here:

        Kiosko.getLosResultados().clear();
        jTextArea1.setText(" ");
    }//GEN-LAST:event_jButtonLimpiarBusquedaActionPerformed

    private void jButtonConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfiguracionActionPerformed
        // TODO add your handling code here:
        PantallaConfiguracionUsuario b = new PantallaConfiguracionUsuario(this, tienda, jLabelUsusarioIniciado.getText());

    }//GEN-LAST:event_jButtonConfiguracionActionPerformed

    private void jButtonAdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdministracionActionPerformed
        // TODO add your handling code here:
        PantallaAdministracion b = new PantallaAdministracion(this, tienda);
        b.setVisible(true);


    }//GEN-LAST:event_jButtonAdministracionActionPerformed

    private void jButtonVerLectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerLectorActionPerformed
        // TODO add your handling code here:
        PantallaLector b = new PantallaLector(this, tienda, productoNumLec, jLabelUsusarioIniciado.getText());
        this.setVisible(false);
    }//GEN-LAST:event_jButtonVerLectorActionPerformed

    private void jButtonBusquedaPorPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBusquedaPorPrecioActionPerformed
        // TODO add your handling code here:

        String comando = jTextFieldPrecioMax.getText();
        Kioskero igor = Kioskero.getInstance();
        try {
            igor.buscaLectoresPrecio(Kiosko.getLectoresDisponibles(), Kiosko.getLosResultados(), Double.parseDouble(comando));
        } catch (KioskoException ex) {
            Logger.getLogger(PantallaInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextArea1.setLineWrap(true);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setText(Kiosko.getLosResultados().get((Kiosko.getLosResultados().size()) - 1).toString());
        productoBusqueda = (Kiosko.getLosResultados().size()) - 1;
    }//GEN-LAST:event_jButtonBusquedaPorPrecioActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {
// TODO add your handling code here:
        Kiosko.guardarDatos();
        Kiosko.guardarDatosLectores();
        Kiosko.guardarDatosLibros();
        Kiosko.guardarDatosVentas();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdministracion;
    private javax.swing.JButton jButtonAtrasLector;
    private javax.swing.JButton jButtonBusqueda;
    private javax.swing.JButton jButtonBusquedaAnterior;
    private javax.swing.JButton jButtonBusquedaAvanzada;
    private javax.swing.JButton jButtonBusquedaPorPrecio;
    private javax.swing.JButton jButtonBusquedaSiguiente;
    private javax.swing.JButton jButtonBusquedaVer;
    private javax.swing.JButton jButtonConfiguracion;
    private javax.swing.JButton jButtonIniciarSesion;
    private javax.swing.JButton jButtonLimpiarBusqueda;
    private javax.swing.JButton jButtonPanelAtras;
    private javax.swing.JButton jButtonPanelSiguiente;
    private javax.swing.JButton jButtonRegistro;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSiguientelibro;
    private javax.swing.JButton jButtonVerLector;
    private javax.swing.JButton jButtonVerlibro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelUsusarioIniciado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldBusqueda;
    private javax.swing.JTextField jTextFieldPanelAutor;
    private javax.swing.JTextField jTextFieldPanelEditorial;
    private javax.swing.JTextField jTextFieldPanelMarca;
    private javax.swing.JTextField jTextFieldPanelModelo;
    private javax.swing.JTextField jTextFieldPanelPrecio;
    private javax.swing.JTextField jTextFieldPanelPrecio2;
    private javax.swing.JTextField jTextFieldPanelTitulo;
    private javax.swing.JTextField jTextFieldPrecioMax;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
